### ISSUE TITLE
Adding Akismet support

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/pirate-forms#100]
If possible, it will be great to add Github support to Pirate Forms to better catch spam.

@rodica-andronache

**Comment by rodica-andronache** [comment]
http://contactform7.com/spam-filtering-with-akismet/

**Comment by selul** [comment]
@contactashish13 can you check how we can do this.

**Comment by contactashish13** [comment]
@selul do we have an API key?

**Comment by selul** [comment]
@ineagu can you help with one for test.

**Comment by HardeepAsrani** [comment]
It should use user's Akismet API to do, like Jetpack does.

**Comment by contactashish13** [comment]
@selul i can think of this approach:

## admin settings
1. the user gets a check box in global settings that says integrate with akismet (global setting only, not for per-forms)
2. if akismet is installed
a. and activated, use the key
b. but not activated, display a message so that user can get a key and activate akismet
3. if akismet is not installed, provide a text box for the user to provide a key (maybe the user wants to use akismet only for this and does not want the plugin)

## sending the email
as the last step before sending the message, validate with akismet. if it fails, show that the message was not sent.

Let me know if this is fine.

**Comment by selul** [comment]
@contactashish13 yes, sounds fine.

**Comment by contactashish13** [comment]
@selul still need an api key. I tried to sign up for one but it asks for credit card details etc.

**Comment by contactashish13** [comment]
@selul thinking about it a little more, users would want to use Akismet if they have gone to the effort of procuring an API key. So maybe we should just ask the users to install and activate Akismet without giving them the option of using an Akismet key for the plugin. What do you think?

**Comment by selul** [comment]
yes, we can use directly the akismet, if is active and licensed.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/200

**Comment by selul** [comment]
@contactashish13 there is some conflict when i try to merge this, can you have a look and solve them?

**Comment by contactashish13** [comment]
@selul have resolved the conflicts

**Comment by selul** [comment]
@contactashish13 there is another one with the akismet support branch.

**Comment by contactashish13** [comment]
@selul sorry, didn't see that one. resolved now.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/204
