### ISSUE TITLE
Clear fields after submit

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#120]
@rodica-andronache I have seen this been asked for a couple of times, we should maybe consider it.

**Comment by michalsvorc** [comment]
Or You could just hide the whole form.pirate_forms through JS (jQuery for some animation) and leave only the success message visible. 

It confuses users because the text they entered stays in the form and looks like it 'went nowhere'. I don't want to create success page on every wp install just to reset form data.

Also adding some action on mail sent (like pirate_form_mail_sent) would be nice so I could hook into it and execute my own javascript (form reset, conversions, etc.)

Thank You

**Comment by selul** [comment]
We will tackle this on the next release.
