### ISSUE TITLE
Attachment field not working without a spam trap option

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#214]
If you choose No spam trap, the attachment field is not working, no popup is opening to upload the file

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/218

the issue was more severe because the attachment field only worked when recaptcha was chosen.

A related issue: I think a lot of customers get confused when they don't see the recaptcha even though they have selected it. Its because the recaptcha is hidden and shown only when an element is clicked. Maybe this behavior needs to be changed. Seems like the code here: https://github.com/Codeinwp/pirate-forms/blob/master/public/js/scripts.js#L4-L22

**Comment by contactashish13** [comment]
@selul this one

**Comment by selul** [comment]
@abaicus @rodica-andronache @ineagu can we do something with the reCaptcha issue   ? Maybe replace with our custom trap version which is much easier to style ?

Thanks !

**Comment by ineagu** [comment]
I think we can have our spam trap as first option somehow?

**Comment by selul** [comment]
@contactashish13 i would like to make the next change in order to assure backwards compatibility and fix this issue. 

1) Add as default value the spam trap.
2) Change value for the reCaptcha setting to something else,  for instance if you were using to check if the recaptcha is enabled using: 
``` 
If( recaptcha is active ) { //show code }
```
you can change in something like this: 
If( recaptcha2 is active ) { //show code }
where recaptch2 is the new value and will not show the hiding efect for the recaptcha. 

Also, you will need to check if they had previously `recaptcha` active and show that code with hiding efect and no longer show the one with `recaptcha2`. 

I hope i made myself clear, if you are in doubt, let me know.

**Comment by contactashish13** [comment]
@selul I'm not sure I understand. The hiding code is in javascript and if we remove that the catpcha will always be visible if it is selected.

**Comment by selul** [comment]
Hmm, i was thinking to find a workaround to now show that for the users who are used to be hidden, but i dont think we can. Let's just remove that js thing, and make the custom trap default.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/229/

Just a note that the theme customizer will also need to be changed.

**Comment by selul** [comment]
@contactashish13 what do you mean by theme customizer ?

**Comment by contactashish13** [comment]
@selul the theme customizers in zerif and hestia that set whether recaptcha needs to be shown - I believe they need to be modified to remove the recaptcha key/secret and so that they send a value of 'custom' instead of 'yes' when the checkbox is unchecked. That will make the custom spam trap enabled by default and not recaptcha

**Comment by selul** [comment]
can you give me an example ? I'm not sure i understand

**Comment by contactashish13** [comment]
![image](https://user-images.githubusercontent.com/12953439/32659218-b4855da2-c643-11e7-81b3-a3ba3566ddfe.png)

**Comment by selul** [comment]
@abaicus can we do this in zerif and hestia ?

**Comment by abaicus** [comment]
I think we can. I don't really understand exactly what should be done, though. I don't know what should be added to the theme. Right now we don't have anything of sorts in hestia.

**Comment by selul** [comment]
@abaicus the things that we can do is: 
1) remove from customizer the hide recaptcha/site key/secret key controls.
2) add a single checkbox, for enable spam trap.
3) style the custom trap according to the theme. 

let me know if you have things clear.

**Comment by ineagu** [comment]
@abaicus can you check this out? I activated hestia with pirate forms and it shows the trap by default, which is good, the bad part is that is not styled properly.

we need to see the behaviour for existing users/zerif

**Comment by selul** [comment]
closing this in favor of #83
