### ISSUE TITLE
default of security

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#237]
@contactashish13 i dont know if this is the actual behavior but i would like at the security section to have the none version as default, not the spam trap or recaptcha.

Let me know if you have any questions.

**Comment by contactashish13** [comment]
@selul the default was none, but the value was inherited from zerif even if zerif was not active. So if a user activates zerif, customizes it, changes the theme and then activates pirate forms, it would still take the values from zerif. I've changed this so that it inherits those options only when the theme is active.

PR: https://github.com/Codeinwp/pirate-forms/pull/239

**Comment by selul** [comment]
good.
