### ISSUE TITLE
can't click on label tooltip, isn't displayed where it should

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-forms#243]
when I go to click on the tooltip, this dissapear : https://www.dropbox.com/s/rxxa159ety99imh/Screenshot%202017-11-28%2019.52.20.png?dl=0

**Comment by selul** [comment]
@contactashish13 can you have a look ? I think we need to find a workaround to show links under the field name or something.

**Comment by contactashish13** [comment]
@selul I'm now using jquery-ui tooltips. Have tested on mac/safari as well and it seems to work well. I've added a class so that it can be styled as needed. PR: https://github.com/Codeinwp/pirate-forms/pull/249

**Comment by selul** [comment]
@contactashish13 for some reason the styling of the new tooltip was missing and looked like this: https://www.dropbox.com/s/jdv1vjhnnhxj817/Screenshot%202017-12-28%2015.31.19.png?dl=0 

I understand that you have added that class to be styled in the future, but by default it needed to look as before.  

If a PR is not final and needs some further editing please let me know before in some way in order to not merge it and release.

You can close it when you see it. 

P.S: I have fixed in the last commit the behavior.

**Comment by contactashish13** [comment]
@selul sure, I'll let you know what all is incomplete or needs your attention.
