### ISSUE TITLE
Wrong display if there are two forms on the same page

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/pirate-forms#59]
If I put the widget in footer sidebar and I also put the shortcode in a page, when I am on that page, the name, email and subject fields from footer sidebar will be displayed in  page content, not in footer.
![selection_001](https://cloud.githubusercontent.com/assets/9929553/14065342/63daf4cc-f42e-11e5-954d-f27073262cca.png)

**Comment by selu91** [comment]
the problem is here: https://github.com/Codeinwp/pirate-forms/blob/production/js/scripts-general.js#L13 

You wrap the name and subject in the same container, finding all the elements with class pirate_forms_three_inputs and collect them in the same container. You can comment that line to see that the issue is no longer there. In order to fix you need to target each form and wrap it.
I've sent a pull request which you can merge it after review.
