### ISSUE TITLE
Review all the options provided by the plugin 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#71]
and see if everything is working

http://prntscr.com/b4q4fb

**Comment by cristian-ungureanu** [comment]
@rodica-andronache ,
I tested  Pirate Forms on MyStock. All options are working fine. I have two mentions though. 
- When I receive the mail from that form here it is how it look: 
![screenshot_2](https://cloud.githubusercontent.com/assets/9929553/18992041/be9c52d2-8724-11e6-8da3-ea098abe73c4.png)
Your mail, Your Email, Subject, Your message are labels for inputs in front end ... It's a little confusing to receive an email like this. It makes more sense instead of displaying those labels to display a hard-coded text, something like Message from: *input_name_from_form* , Email: *input_email_from_form*, Message:  *input_message_from_form*. If the user sets the label for message field like "Hello, tell us what you need" , they will receive in email Hello, tell us what you need : *message* 

- In SMTP settings, the password is visible http://prntscr.com/co5qzv

**Comment by rodica-andronache** [comment]
Ok , thank you :) Maybe we'll improve the layout of the message in the future, but right now, I don't think we'll invest time in that
